theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
use_nag = true
nag_path = "i3-nagbar"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "/{available}"

[[block]]
block = "disk_space"
path = "/home"
alias = "home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "~{available}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total} ({mem_total_used_percents})"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{power} {percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
